"use client";
import AppShell from "@/components/AppShell";
import { addDoc, collection, doc, onSnapshot, updateDoc } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { useEffect, useState } from "react";
import type { Inventaris, Peminjaman, Warga } from "@/lib/types";
export default function PeminjamanPage(){
 const [items,setItems]=useState<Inventaris[]>([]),[warga,setWarga]=useState<Warga[]>([]),[rows,setRows]=useState<Peminjaman[]>([]);
 const [form,setForm]=useState({inventoryId:"",wargaId:"",jumlah:1,tanggalPinjam:"",tanggalKembali:"",catatan:""}); const [show,setShow]=useState(false);
 useEffect(()=>{const a=onSnapshot(collection(db,"inventaris"),s=>setItems(s.docs.map(d=>({id:d.id,...d.data()} as Inventaris))));const b=onSnapshot(collection(db,"warga"),s=>setWarga(s.docs.map(d=>({id:d.id,...d.data()} as Warga))));const c=onSnapshot(collection(db,"peminjaman"),s=>setRows(s.docs.map(d=>({id:d.id,...d.data()} as Peminjaman))));return()=>{a();b();c()}},[]);
 async function save(e:React.FormEvent){e.preventDefault();const i=items.find(x=>x.id===form.inventoryId),w=warga.find(x=>x.id===form.wargaId);if(!i||!w)return;await addDoc(collection(db,"peminjaman"),{...form,inventoryName:i.nama,wargaName:w.nama,status:"Menunggu"});setShow(false)}
 async function approve(x:Peminjaman){await updateDoc(doc(db,"peminjaman",x.id!),{status:"Disetujui",disetujuiOleh:"admin"})}
 return <AppShell><div className="flex justify-between mb-5"><div><h1 className="text-2xl font-bold">Peminjaman Inventaris</h1><p className="text-slate-500 text-sm">Kelola permintaan peminjaman warga.</p></div><button className="btn btn-primary" onClick={()=>setShow(true)}>+ Peminjaman Baru</button></div>
 <div className="card overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{["Warga","Barang","Jumlah","Pinjam","Kembali","Status","Aksi"].map(h=><th className="text-left p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(x=><tr className="border-t" key={x.id}><td className="p-3 font-medium">{x.wargaName}</td><td className="p-3">{x.inventoryName}</td><td className="p-3">{x.jumlah}</td><td className="p-3">{x.tanggalPinjam}</td><td className="p-3">{x.tanggalKembali}</td><td className="p-3"><span className="badge bg-amber-50 text-amber-700">{x.status}</span></td><td className="p-3">{x.status==="Menunggu"&&<button onClick={()=>approve(x)} className="text-blue-600 font-semibold">Setujui</button>}</td></tr>)}</tbody></table>{rows.length===0&&<div className="p-10 text-center text-slate-500">Belum ada peminjaman.</div>}</div>
 {show&&<div className="fixed inset-0 bg-black/40 grid place-items-center p-4 z-50"><div className="bg-white rounded-2xl p-6 w-full max-w-lg"><div className="flex justify-between mb-5"><h2 className="text-xl font-bold">Peminjaman Baru</h2><button onClick={()=>setShow(false)}>✕</button></div><form onSubmit={save} className="space-y-3"><div><label className="text-sm">Warga</label><select className="input mt-1" required value={form.wargaId} onChange={e=>setForm({...form,wargaId:e.target.value})}><option value="">Pilih warga</option>{warga.map(x=><option key={x.id} value={x.id}>{x.nama} — {x.nik}</option>)}</select></div><div><label className="text-sm">Barang</label><select className="input mt-1" required value={form.inventoryId} onChange={e=>setForm({...form,inventoryId:e.target.value})}><option value="">Pilih barang</option>{items.filter(x=>x.tersedia>0).map(x=><option key={x.id} value={x.id}>{x.nama} — tersedia {x.tersedia}</option>)}</select></div><div><label className="text-sm">Jumlah</label><input className="input mt-1" type="number" min="1" value={form.jumlah} onChange={e=>setForm({...form,jumlah:+e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><label className="text-sm">Tanggal Pinjam</label><input className="input mt-1" type="date" required value={form.tanggalPinjam} onChange={e=>setForm({...form,tanggalPinjam:e.target.value})}/></div><div><label className="text-sm">Tanggal Kembali</label><input className="input mt-1" type="date" required value={form.tanggalKembali} onChange={e=>setForm({...form,tanggalKembali:e.target.value})}/></div></div><textarea className="input" placeholder="Catatan" value={form.catatan} onChange={e=>setForm({...form,catatan:e.target.value})}/><button className="btn btn-primary w-full">Simpan</button></form></div></div>}
 </AppShell>
}
